id: P000210
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །རྣམ་རིག་གྲུབ་པའི་རྒྱན་ཞེས་བྱ་བ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། རེད་མདའ་བ་གཞོན་ནུ་བློ་གྲོས།
  layers:
  - book_title
  - author
  - quotation
  id: IBA-RD-2-1
web_metadata:
  title:
    en: The Ornament of Cittamatra
    bo: རྣམ་རིག་གྲུབ་པའི་རྒྱན།
  collection:
    en: IBA Rendawa Series–  Book 2
    bo: རེད་མདའ་བ་རྩོམ་བྲིས།–  དེབ། ༢
  author:
    en: Rendawa Shonu Lodro
    bo: རེད་མདའ་བ་གཞོན་ནུ་བློ་གྲོས།
  pusblisher:
    en: IBA Publications
    bo: རྒྱལ་ཡོངས་གསུང་རབ་སློབ་གཉེར་ཁང་།
  sku: IBA-RD-2-1
  category:
    en: Abhidharma
    bo: ཆོས་མངོན་པ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: IBA-RD-2-1.epub
  description:
    en: The Ornament of Cittamatra present the ideology of mind only school of Buddhism.
      This text specifically emphasizes on the paths and its obstructions.
    bo: སེམས་ཙམ་པའི་གྲུབ་མཐའི་སྐོར།
